site_name: TTRPG CLI
site_url: https://kc-ou.github.io/TTRPG-CLI
repo_url: https://github.com/KC-OU/TTRPG-CLI
repo_name: KC-OU/TTRPG-CLI

# navigation
nav:
  - Home: "index.md"
  - D&D 5e:
      - Character-Creation.md

theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material
  features:
    # QOL features
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    - navigation.indexes
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
  logo: assets/logo.png
  favicon: images/favicon.png
  font:
    text: Raleway
    code: Ubuntu Mono

  # //TODO: Need to change the fonts
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "blue"
      accent: "light blue"
      toggle:
        icon: material/brightness-4
        name: Toggle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: "blue"
      accent: "light blue"
      toggle:
        icon: material/brightness-7
        name: Toggle dark mode
markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - neoteroi.cards
